AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the NewRelic::Agent::Configuration resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.newrelic.aws.cfn.resources.agent.configuration.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/newrelic-agent-configuration-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.newrelic.aws.cfn.resources.agent.configuration.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/newrelic-agent-configuration-handler-1.0-SNAPSHOT.jar

