---
AWSTemplateFormatVersion: '2010-09-09'
Description: Shows how to create a tag against a code ref (branch or commit) in GitLab
Resources:
  SamplePolicyChannelAssociation:
    Type: NewRelic::Alert::PolicyChannelAssociation
    Properties:
      AccountId: 3504143
      ChannelIds: [342613, 342614]
      PolicyId: 646591
